config.json.example, package.json, src/index.js
=> #3: default labels (closes #3)

package.json, src/index.js
=> #5: enforce "macro" label (closes #5)

src/index.js, src/processors/labels.js, src/processors/subIssues.js
=> #17: Add macro label when processing sub-issues (closes #17)

src/index.js, src/processors/labels.js, src/processors/subIssues.js
=> #19: [labels] add InReview and WIP to pulls too (closes #19)

src/md-renderer.js, src/processors/subIssues.js
=> #21: sub-issues list items broken (closes #21)

src/processors/labels.js
=> #8: Sync Issue and PR labels (closes #8)

src/processors/labels.js
=> #27: disassociate closed but not merged PR from Issue (closes #27)

config-ci.json
=> #30: fix config-ci after merge of labonline and qia in new super repo aliniq (closes #30)

src/processors/subIssues.js
=> #32: [sub-issues] crash if `issue.body` is `null` (closes #32)

src/processors/labels.js
=> #34: GET issue for pull_request sometimes fails (closes #34)

src/processors/subIssues.js
=> #29: support both ← and <- (closes #29)

src/processors/gifs.js, src/processors/index.js
Issue #39
**test plan**
see this PR: https://github.com/buildo/github-prettifier/pull/36
=> #39: No GIFs in merged PRs :( (closes #39)

package.json, src/processors/gifs.js, src/processors/labels.js, src/processors/subIssues.js, src/validators.js
Issue #49 
**test plan**
any action by @nemobot on this PR was done by local process
=> #49: define tcomb models and use validators to filter event types (closes #49)

package.json, src/index.js, src/processors/gifs.js, src/processors/labels.js, src/processors/subIssues.js, src/validators.js
Issue #46
based on #50 (see last two commits)
**test plan**
- artificially tried delaying every event of `5000`ms --> verified they were actually delayed :white_check_mark: 
- used local @nemobot on this PR
=> #46: Implement standard way to handle delayed processors (closes #46)

package.json, src/config.js, src/index.js, src/processors/gifs.js, src/processors/index.js, src/processors/labels.js, src/processors/reminders.js, src/processors/subIssues.js, src/validators.js
Issue #47
based on #48 
**test plan**
tested successfully on this issue using label `web`: https://github.com/buildo/github-prettifier/issues/51
=> #47: [reminders] remind to add "web/api/..." topic labels if missing (closes #47)

config-ci.json
=> #57: add "omnilab-feedback" to topic labels (closes #57)

src/processors/index.js, src/processors/state.js, src/processors/subIssues.js, src/validators.js
Issue #62
**test plan**
test on https://github.com/buildo/nemobot/issues/54
- close 53 and 51 --> nemobot closes 54
- open 53 --> nemobot opens 54
- close 53 --> nemobot closes 54
- open 51 --> nemobot opens 54
- open 53 --> nemobot does nothing (it was already opened)
=> #62: [state] should close/reopen macro issues based on sub-issues status (closes #62)

src/templates/index.js, templates/pr.md
Issue #67 
**test plan**
this `http://e5a4d1ec.ngrok.io/templates?t=pr&associatedIssueNumber=234` returns
```json
{"pr":{"body":"Issue #234\n\n## Test Plan\n\n### tests performed\n{A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.\n\nThese results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}\n\n#### cross browser compatibility\n{If applicable, please write on which browsers you tested this. A good test plan should include a few tests on different browsers among the supported ones.}\n\n### tests not performed (domain coverage)\n{At times not everything can be tested, and writing what hasn't been tested is just as …
```
=> #67: [templates] add PR template (closes #67)

src/processors/reminders.js
Issue #56
- added label `web` to this repo
- open issue #70  without labels
- deployed `nemobot`:
- local `nemobot`:
=> #56: [reminder] Only show repo-specific topic labels in reminder (closes #56)

src/processors/reminders.js, src/validators.js
Issue #63
- auto-assign PR without modifying testplan template
- `nemobot` adds comment to remind test-plan
- modify test-plan template and redeliver webhook
- `nemobot` does not comment
- regression test:
- redeliver new issue event without label `web`
- `nemobot` adds comment to remind topic labels
=> #63: [reminder] remind test-plan when PR is assigned (closes #63)

src/processors/labels.js
Issue #59
- add `WIP` to #72 and redeliver closed event
- `nemobot` removes `WIP`
- add `WIP` and `InReview` to #63 and redeliver closed event
- `nemobot` removes `WIP` and `InReview`
=> #59: [labels] should always remove WIP/InReview in issues too (closes #59)
